[2023-06-11 03:54:25,183] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 01_unscheduled.fetch_events manual__2023-06-11T03:54:24.205713+00:00 [queued]>
[2023-06-11 03:54:25,191] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 01_unscheduled.fetch_events manual__2023-06-11T03:54:24.205713+00:00 [queued]>
[2023-06-11 03:54:25,192] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-11 03:54:25,193] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-06-11 03:54:25,194] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-11 03:54:25,202] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): fetch_events> on 2023-06-11 03:54:24.205713+00:00
[2023-06-11 03:54:25,207] {standard_task_runner.py:52} INFO - Started process 469 to run task
[2023-06-11 03:54:25,209] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '01_unscheduled', 'fetch_events', 'manual__2023-06-11T03:54:24.205713+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/unscheduled.py', '--cfg-path', '/tmp/tmpjt5mx4d0', '--error-file', '/tmp/tmplbejrezi']
[2023-06-11 03:54:25,211] {standard_task_runner.py:80} INFO - Job 69: Subtask fetch_events
[2023-06-11 03:54:25,261] {task_command.py:371} INFO - Running <TaskInstance: 01_unscheduled.fetch_events manual__2023-06-11T03:54:24.205713+00:00 [running]> on host fd847b0d0eb3
[2023-06-11 03:54:25,309] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=01_unscheduled
AIRFLOW_CTX_TASK_ID=fetch_events
AIRFLOW_CTX_EXECUTION_DATE=2023-06-11T03:54:24.205713+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-11T03:54:24.205713+00:00
[2023-06-11 03:54:25,311] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-11 03:54:25,314] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p /data/events && curl -o /data/events.json http://events_api:5000/events']
[2023-06-11 03:54:25,323] {subprocess.py:85} INFO - Output:
[2023-06-11 03:54:25,327] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/data’: Permission denied
[2023-06-11 03:54:25,329] {subprocess.py:96} INFO - Command exited with return code 1
[2023-06-11 03:54:25,341] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-11 03:54:25,345] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=01_unscheduled, task_id=fetch_events, execution_date=20230611T035424, start_date=20230611T035425, end_date=20230611T035425
[2023-06-11 03:54:25,355] {standard_task_runner.py:97} ERROR - Failed to execute job 69 for task fetch_events (Bash command failed. The command returned a non-zero exit code 1.; 469)
[2023-06-11 03:54:25,385] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-11 03:54:25,416] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
